fix: Correct invalid podspec attribute from 'visionos' to 'ios'
react-native-clipboard/clipboard pull request #236
Opened 2024-04-12 05:05 UTC by OOWGNOD

## Overview
While installing the RNCClipboard pod, an error was encountered indicating that the `visionos` method is undefined for Pod::Specification. This was due to a typographical error in the RNCClipboard.podspec file where `visionos` was mistakenly used instead of `ios`.

## Changes Made
- Changed `visionos` to `ios` in the podspec file to correct the typo and resolve the pod installation error.

## Impact
This fix will allow users to install the RNCClipboard pod without encountering the "undefined method `visionos`" error, thereby improving the installation experience and ensuring compatibility with CocoaPods standards.

## Testing
After making this change, `pod install` was executed successfully without errors. This ensures that the fix addresses the issue as intended.

Please review the changes and merge them if everything is in order. This should help anyone facing similar issues with pod installation errors.

2024-04-12 05:07 UTC, OOWGNOD commented
Hello,

While reviewing the `RNCClipboard.podspec` file, I noticed that `s.visionos.source_files` was incorrectly specified. Initially, I considered modifying this line to `s.ios.source_files`, but I found that this exact line was already present above in the podspec file. To avoid redundancy and confusion, I removed the incorrect `s.visionos.source_files` line. This ensures that the podspec file is clean and error-free without any duplicate entries.

Thank you for reviewing this pull request and please let me know if there are any other adjustments you would like me to make.

2024-04-12 20:50 UTC, shawnlauzon commented
I'm hitting this same error, looking forward to this fix being integrated.

2024-04-16 03:49 UTC, OOWGNOD commented
@shawnlauzon 's suggestion to update Cocoapods proved to be the correct solution for resolving the issue with the invalid podspec attribute 'visionos'. Following his advice, I updated Cocoapods, which effectively resolved the problem.

Therefore, I am closing this pull request as the update to Cocoapods has addressed the issue without the need for any changes to the library's code. I am extremely grateful for the insight provided by Shawn during this process.

Thank you sincerely!

2024-04-16 10:32 UTC, kbqdev commented
Still exist.
 "react-native": "0.71.6",
 "@react-native-clipboard/clipboard": "^1.14.0" and newest cocapods

2024-04-16 10:37 UTC, OOWGNOD commented
I will reopen the pull request as there may be different opinions on this matter.

2024-04-22 05:07 UTC, Naturalclar commented
@Saadnajmi would you be able to confirm if the change is good?
im not facing the problem locally and want to make sure that it wont break things on visionos side

2024-04-22 06:38 UTC, Saadnajmi commented
`s.visionos.files` and `s.ios.files` are indeed mutually exclusive. However, I think only cocoapods 1.13+ supports visionOS. I don't think this change is the right one?

2024-04-25 13:48 UTC, joaomantovani commented
Same issue here, I made it work using EAS specifying the cocoa pods version on eas.json

```json
{
  "cli": {
    "version": ">= 3.13.3"
  },
  "build": {
    "production": {
      "ios": {
        "cocoapods": "1.15.2"
      }
    }
  }
}
```

2024-05-03 07:25 UTC, Mihai-github commented
updating the cocopods version from 1.12.0 to 1.15.2 fixed my issue also

2024-05-04 01:07 UTC, Saadnajmi requested changes
This change is incorrect, see https://github.com/react-native-clipboard/clipboard/pull/236#issuecomment-2068599670

2024-05-04 06:40 UTC, OOWGNOD reviewed
Thank you for your feedback. I will review the comments in #236 and make the necessary changes.

2024-05-04 06:50 UTC, closed without merging

2024-05-07 12:09 UTC, kigh143 commented
> updating the cocopods version from 1.12.0 to 1.15.2 fixed my issue also

Updated the version but it failed to work, i went ahead to comment out the line and it worked fine.